[package]
name = "rs-dx12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
winit = "0.29"
simple_logger = { version = "4.2.0", default_features = false }
